export enum ROUTES {
  HOME = "/",
  SERVICES = "/services",
  PARTNERS = "/partners",
  TESTIMONIALS = "/testimonials",
  LOGIN = "/auth/login",
  LOGOUT = "/auth/logout",
  OTP = "/auth/verify-otp",
  SET_PHONE = "/auth/set-phone",
  REGISTER = "/auth/register",
  SIGNUP = "/auth/register",

  SERVICE_PROVIDER_REGISTRATION_FORM = "/service-provider/register",
  SERVICE_PROVIDER_PROFILE = "/service-provider/profile",
  DASHBOARD = "/dashboard",
  PROFILE = "/profile",
  SETTINGS = "/settings",
  ABOUT = "/about",
  CONTACT = "/contact",
  PRIVACY_POLICY = "/privacy-policy",
  TERMS_OF_SERVICE = "/terms-of-service",
  HELP = "/help",
  FAQ = "/faq",
  BLOG = "/blog",
  NOT_FOUND = "/404",
}
